config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "pages#index"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts  do
    resources :postcomments
  end
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
		belongs_to :user
		belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomments
	
	validates :title, length: { in: 1..15}
	validates :title, :body, presence: true	
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	
	validates :text, length: { in: 1..30}
	validates :text, presence: true	

end

app/models/user.rb
      class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :postcomments
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates :password, confirmation: true
         validates :nickname, length: { maximum: 10 }
         validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
         validates :password, :email, :nickname, presence:true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :devise_sign_up_params, if: :devise_controller?
  protect_from_forgery with: :exception


private

  def devise_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :nickname, :avatar])	
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@users = User.all 
  	@posts = Post.all
  end
end

app/controllers/postcomments_controller.rb
class PostcommentsController < ApplicationController
before_action :authenticate_user!

	def create
		pp params[:postcomment][:post_id] = params[:post_id]
		pp params[:postcomment][:user_id] = current_user.id
		@comment = Postcomment.create(postcomments_params)
		if @comment.save
			redirect_to post_path(params[:post_id])
		else
			@comment.errors.full_messages.each do |msg|
				@msg = msg
			end
			flash[:notice] = "#{@msg}"
			redirect_to post_path(params[:post_id])
		end
	end

	private

	def postcomments_params
		params.require(:postcomment).permit(:user_id, :post_id, :text)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show,:edit,:update,:destroy]
  
      def new
       @post = Post.new
  end 

      def show
    @comments = Postcomment.where(post_id: @post.id)
  end

      def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end

  end
  
     def destroy
    @post.destroy
    redirect_to root_path
  end

     def edit
  end

     def update
    @post.update(post_params)
    redirect_to root_path
  end

  private
      def post_params
      params.require(:post).permit(:user_id,:title,:body)
  
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<style type="text/css">
html {
  position: relative;
 
}

body {
  
    background-color: Gainsboro;
}

.footer {
  position: absolute;
  width: 100%;
  height: 145px;
  background-color: #111;
  text-align: center;
}
.container{
  margin-top: 10px;
  color: #ddd;
  width: 100%;
}

.fa-twitter {
    color: #4099FF;
}

.fa-facebook {
    color: #3B5998;
}

.fa-youtube-play {
    color: #e52d27;
}

.fa {
    opacity: 0.7;
    transition: 1s;
    -webkit-transition: 1s;
}

.fa:hover{
    opacity: 1;
    transition: 1s;
    -webkit-transition: 1s;
</style>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <div class="footer">
      <div class="container">
              <h3>Blog Andriy Savic</h3>
              <a href='https://facebook.com'><i class="fa fa-facebook fa-3x fa-fw"></i></a>
              <a href='https://twitter.com'><i class="fa fa-twitter fa-3x fa-fw"></i></a>
              <a href='https://www.youtube.com'><i class="fa fa-youtube-play fa-3x fa-fw"></i></a>

     </span>

      </div>

    </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
     <%= link_to "Blog Savic", root_path, class:"navbar-brand" %>
    </div>
   

    <ul class="nav navbar-nav navbar-right">
    <% if current_user.nil? %>
    <li>
    <%= link_to user_session_path do %>
      <i class="glyphicon glyphicon-user"></i> Login
      <%end%>
      </li>
      <% else %> 
      <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="glyphicon glyphicon-log-in"></i> Logout
  <%end%>
      </li>
       <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Savic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/index.html.erb
<center><%= link_to "Create new post", new_post_path, class: "btn btn-info" %>
<div class="posts">
<% @posts.each do |post| %><br />
<hr>


<h1><%= link_to post.title, post_path(post.id)%></h1>
<p>
	<%= image_tag post.user.avatar.url(:thumb), width: 50, height: 50 %>
	Author: <%= post.user.nickname%>  |   
    Create at: <%= post.created_at%>
</p>
<p><%= post.body %></p>
<% if current_user != nil and current_user.id == post.user_id %>
<p><%= link_to "Edit", edit_post_path(post.id) %>
 or 
 <%= link_to "Delete", post_path(post.id), data: {confirm: 'Are you sure?'}, method: :delete %></p>
<% end %>
<% end %>
</div>
</center>

app/views/posts/_form.html.erb
<p><%= f.label :title %></p>
<%= f.text_field :title %><br />

<p><%= f.label :body %></p>
<%= f.text_area :body, cols: 40, rows: 20 %><br />

<p><%= f.submit "Save"%></p>

app/views/posts/edit.html.erb
<%= form_for :post, url:post_path, method: :patch do |f| %>
<% if @post.errors.any? %>
<% @post.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
<% end %>

<%= render 'posts/form', f:f %>

<% end %>

app/views/posts/new.html.erb
<%= form_for :post, url: posts_path do |f| %>
<% if @post.errors.any? %>
<% @post.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
<% end %>

<%= render 'posts/form', f:f %>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<% @comments.each do |comment| %>
<p>User <b><%= comment.user.nickname %></b> write: </p>
<%= comment.text %>
<hr>
<% end %>
	<%= form_for :postcomment, url: post_postcomments_path(post_id: @post.id) do |f| %>
<% if flash[:notice] %>
	<div ><%= flash[:notice] %></div>
<% end %>
	<p><%= f.label "Write your comment" %></p>
	<%= f.text_area :text, cols: 20, rows: 5 %></br>

	<p><%= f.submit "Send"%></p>
	
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>